import type { Task, DailySummary } from "./types"

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Estudar React Hooks",
    description: "Revisar useState, useEffect e custom hooks",
    category: "study",
    startDate: new Date(),
    endDate: new Date(),
    startTime: "14:00",
    endTime: "16:00",
    isPeriodic: false,
    status: "in-progress",
    progress: 33,
    elapsedTime: 2700,
    estimatedTime: 7200, // 2 horas
    expectedDifficulty: "medium",
    expectedSatisfaction: 4,
    subtasks: [
      { id: "1-1", title: "Revisar documentação oficial", estimatedTime: 1800, elapsedTime: 1800, completed: true, completedAt: new Date() },
      { id: "1-2", title: "Fazer exercícios práticos", estimatedTime: 2700, elapsedTime: 900, completed: false },
      { id: "1-3", title: "Criar projeto exemplo", estimatedTime: 2700, elapsedTime: 0, completed: false },
    ],
    currentSubtaskIndex: 1,
    tags: ["react", "frontend"],
    importance: "urgent-important",
    order: 0,
  },
  {
    id: "6",
    title: "Ler Livro de Ficção",
    description: "Continuar leitura do capítulo 5",
    category: "leisure",
    startDate: new Date(),
    endDate: new Date(),
    isPeriodic: false,
    status: "paused",
    progress: 30,
    elapsedTime: 1200,
    expectedDifficulty: "easy",
    expectedSatisfaction: 5,
    tags: ["lazer", "leitura"],
    importance: "not-urgent-not-important",
    order: 5,
  },
  {
    id: "7",
    title: "Curso de TypeScript",
    description: "Módulo 3: Tipos Avançados",
    category: "study",
    startDate: new Date(),
    endDate: new Date(),
    isPeriodic: false,
    status: "paused",
    progress: 66,
    elapsedTime: 4500,
    estimatedTime: 5400, // 1h30m
    expectedDifficulty: "hard",
    expectedSatisfaction: 4,
    subtasks: [
      { id: "7-1", title: "Estudar Generics", estimatedTime: 1800, elapsedTime: 1800, completed: true, completedAt: new Date() },
      { id: "7-2", title: "Praticar Utility Types", estimatedTime: 1800, elapsedTime: 1800, completed: true, completedAt: new Date() },
      { id: "7-3", title: "Fazer projeto", estimatedTime: 1800, elapsedTime: 900, completed: false },
    ],
    currentSubtaskIndex: 2,
    tags: ["typescript", "programação"],
    importance: "not-urgent-important",
    order: 6,
  },
  {
    id: "2",
    title: "Treino de Força",
    description: "Treino de membros superiores",
    category: "training",
    startDate: new Date(Date.now() + 3600000),
    endDate: new Date(Date.now() + 3600000),
    startTime: "18:00",
    endTime: "19:30",
    isPeriodic: true,
    periodicInterval: { value: 2, unit: "days" },
    status: "pending",
    progress: 0,
    expectedDifficulty: "hard",
    expectedSatisfaction: 5,
    tags: ["saúde", "fitness"],
    importance: "not-urgent-important",
    order: 1,
  },
  {
    id: "3",
    title: "Reunião de Projeto",
    description: "Alinhamento com equipe sobre novas features",
    category: "work",
    startDate: new Date(Date.now() + 7200000),
    endDate: new Date(Date.now() + 7200000),
    startTime: "10:00",
    endTime: "11:00",
    isPeriodic: false,
    status: "pending",
    progress: 0,
    expectedDifficulty: "easy",
    expectedSatisfaction: 3,
    tags: ["trabalho", "reunião"],
    importance: "urgent-not-important",
    order: 2,
  },
  {
    id: "4",
    title: "Beber 2L de Água",
    description: "Meta diária de hidratação",
    category: "water",
    startDate: new Date(),
    endDate: new Date(),
    isPeriodic: true,
    periodicInterval: { value: 1, unit: "days" },
    status: "pending",
    progress: 60,
    expectedSatisfaction: 5,
    tags: ["saúde", "hábito"],
    importance: "not-urgent-important",
    order: 3,
  },
  {
    id: "5",
    title: "Preparar Refeições",
    description: "Meal prep para a semana",
    category: "food",
    startDate: new Date(Date.now() + 10800000),
    endDate: new Date(Date.now() + 10800000),
    startTime: "12:00",
    endTime: "14:00",
    isPeriodic: true,
    periodicInterval: { value: 1, unit: "weeks" },
    status: "pending",
    progress: 0,
    expectedDifficulty: "medium",
    expectedSatisfaction: 4,
    tags: ["alimentação", "planejamento"],
    importance: "not-urgent-not-important",
    order: 4,
  },
]

export const mockCompletedTasks: Task[] = [
  {
    id: "c1",
    title: "Meditação Matinal",
    description: "15 minutos de meditação guiada",
    category: "health",
    startDate: new Date(Date.now() - 86400000),
    endDate: new Date(Date.now() - 86400000),
    startTime: "07:00",
    endTime: "07:15",
    isPeriodic: true,
    periodicInterval: { value: 1, unit: "days" },
    status: "completed",
    progress: 100,
    elapsedTime: 900,
    expectedDifficulty: "easy",
    expectedSatisfaction: 5,
    actualDifficulty: "easy",
    actualSatisfaction: 5,
    tags: ["saúde", "mindfulness"],
    importance: "not-urgent-important",
    order: 0,
    completedAt: new Date(Date.now() - 82800000),
  },
  {
    id: "c2",
    title: "Revisar Pull Requests",
    description: "Code review dos PRs pendentes",
    category: "work",
    startDate: new Date(Date.now() - 86400000),
    endDate: new Date(Date.now() - 86400000),
    startTime: "09:00",
    endTime: "10:00",
    isPeriodic: false,
    status: "completed",
    progress: 100,
    elapsedTime: 3600,
    expectedDifficulty: "medium",
    expectedSatisfaction: 3,
    actualDifficulty: "hard",
    actualSatisfaction: 4,
    tags: ["trabalho", "código"],
    importance: "urgent-important",
    order: 1,
    completedAt: new Date(Date.now() - 79200000),
  },
  {
    id: "c3",
    title: "Organizar Escritório",
    description: "Limpar e organizar mesa de trabalho",
    category: "home",
    startDate: new Date(Date.now() - 172800000),
    endDate: new Date(Date.now() - 172800000),
    isPeriodic: false,
    status: "completed",
    progress: 100,
    elapsedTime: 1800,
    expectedDifficulty: "easy",
    expectedSatisfaction: 4,
    actualDifficulty: "easy",
    actualSatisfaction: 5,
    tags: ["casa", "organização"],
    importance: "not-urgent-not-important",
    order: 2,
    completedAt: new Date(Date.now() - 169200000),
  },
]

export const mockSummary: DailySummary = {
  date: new Date(),
  totalTasks: 10,
  completedTasks: 3,
  byCategory: {
    study: 3,
    work: 1,
    training: 1,
    leisure: 1,
    water: 1,
    food: 1,
    home: 1,
    health: 1,
    others: 0,
  },
}
